### PR TITLE
Tidy up emoji

### PR DESCRIPTION
**Pull request by emiphi**
Tidy up some of the emojis:
- Maintain aspect ratios on resize
- Fix background transparency of existing images
- Dark mode friendly
- Add k8s.png

### CODE REVIEW

**Comment by jfhbrook** [comment]
I think the mysql icon might have issues with a light background, if people have that on discord? Otherwise this all looks great.

One thing worth considering is that the current thing won't replace images and I kinda wanna figure out if there's a way I can get CI to handle this instead of running stuff manually. Maybe I can get python to compare order of commit SHAs from a flat file? If you have the patience for that I can take a look this weekend, otherwise we can just delete all of the existing ones manually before merging this - or I can get off my butt and get my dev env set up on my new laptop. Either way. Which do you prefer?

**Comment by jfhbrook** [comment]
The background on that is that Discord doesn't expose a hash we can use to obviously avoid uploading a new file and I don't store any state anywhere, so we either have to delete and replace every icon or only upload the ones with new names. When I wrote this I hoped that icon replacement was a rare use case but in retrospect the idea that people wouldn't upload shitty icons is really naive!

**Comment by jfhbrook** [comment]
It could be really fun to build migrations on top of getting github actions to commit and push https://github.com/marketplace/actions/github-commit-push probably the most sensible way to store state in a contained way but also delightfully hacky

**Comment by emiphi** [comment]
> I think the mysql icon might have issues with a light background, if people have that on discord? Otherwise this all looks great.

This is a valid point and I also changed the Kafka icon wo be white instead of black to be better suited to the default dark mode. It's the perennial problem of logos not being designed for use on both light and dark backgrounds - I'll see if I can find a blue-ish one to replace it that should work. Kafka is less obvious, as it's officially either black or white.

> If you have the patience for that I can take a look this weekend, otherwise we can just delete all of the existing ones manually before merging this - or I can get off my butt and get my dev env set up on my new laptop. Either way. Which do you prefer?

I'm in no huge rush, if you think you'll have time this weekend then we can see where we are next week and go from there.

> It could be really fun to build migrations on top of getting github actions to commit and push https://github.com/marketplace/actions/github-commit-push probably the most sensible way to store state in a contained way but also delightfully hacky

That sounds pretty promising. Get the most recent record for a given filename from an append-only log. If it is missing or the file in the branch has a different SHA, create or replace it on discord and append the row (filename, sha) to the log. After deployment, commit and push the log file.

**Comment by jfhbrook** [comment]
I'm going to merge this as-is and rebase #5 against it. Thanks!

**Pull request merged**
